### PR TITLE
Run ansible prerequisites to download necessary files.

### PR DESCRIPTION
**Pull request by cajbecu**

### CODE REVIEW

**Comment by deimosfr** [comment]
I do not want to force the prerequisite. If Python is already installed by another way on the machine, I do not want to enforce Pypy installation

**Comment by deimosfr** [comment]
However, if you really want it, please add a when statement with a default variable

**Comment by deimosfr** [comment]
I've did it, please take a look at the latest version

**Comment by cajbecu** [comment]
Thanks @deimosfr !

**Pull request closed without merging**
